[package]
name = "reinforcement"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
rand_distr = "0.5"
array_vector_space = {git = "https://github.com/xayon40-12/array_vector_space.git"}
